version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: userland
    ports:
      - 54320:5432
    restart: always
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql/data
  pg-admin:
    image: dpage/pgadmin4
    environment:
      POSTGRES_DB: userland
      PGADMIN_DEFAULT_EMAIL: user@userland.com
      PGADMIN_DEFAULT_PASSWORD: userlandpassword
    volumes:
      - ./tmp/pgadmin:/var/lib/pgadmin
    links:
      - db
    depends_on:
      - db
    ports:
      - 8001:80
  go-server:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/userland/
    depends_on:
      - db
    links:
      - db
    

