package profile

const (
	REQUEST_BODY_UNDECODABLE                   = 100
	UNABLE_TO_UPDATE_PROFILE                   = 201
	UNABLE_TO_EXEC_UPDATE_EMAIL_QUERY          = 202
	CHANGE_PASSWORD_PASSWORD_NOT_MATCH         = 203
	CHANGE_PASSWORD_INCORRECT_CURRENT_PASSWORD = 204
	DELETE_ACCOUNT_INCORRECT_PASSWORD          = 205
)
