package profile

const (
	REQUEST_BODY_UNDECODABLE                   = 100
	UNABLE_TO_UPDATE_PROFILE                   = 201
	UNABLE_TO_EXEC_UPDATE_EMAIL_QUERY          = 202
	CHANGE_PASSWORD_PASSWORD_NOT_MATCH         = 203
	CHANGE_PASSWORD_PASSWORD_INVALID           = 204
	CHANGE_PASSWORD_INCORRECT_CURRENT_PASSWORD = 205
	DELETE_ACCOUNT_INCORRECT_PASSWORD          = 206
	PICTURE_FAILED_TO_EXEC_QUERY               = 207
	PICTURE_CANNOT_BE_FETCHED_FROM_FORM        = 208
	PICTURE_CANNOT_BE_READ                     = 209
)
