package profile

const (
	REQUEST_BODY_UNDECODABLE                   = 100
	UNABLE_TO_UPDATE_PROFILE                   = 201
	USER_INFO_INVALID                          = 202
	UNABLE_TO_EXEC_UPDATE_EMAIL_QUERY          = 203
	EMAIL_INVALID                              = 204
	CHANGE_PASSWORD_PASSWORD_NOT_MATCH         = 205
	CHANGE_PASSWORD_PASSWORD_INVALID           = 206
	CHANGE_PASSWORD_INCORRECT_CURRENT_PASSWORD = 207
	DELETE_ACCOUNT_INCORRECT_PASSWORD          = 208
	PICTURE_FAILED_TO_EXEC_QUERY               = 209
	PICTURE_CANNOT_BE_FETCHED_FROM_FORM        = 210
	PICTURE_CANNOT_BE_READ                     = 211
)
