package auth

const (
	REQUEST_BODY_UNDECODABLE               = 100
	REGISTRATION_BODY_INCOMPLETE           = 101
	REGISTRATION_BODY_INVALID              = 102
	REGISTRATION_PASSWORD_NOT_MATCH        = 103
	REGISTRATION_UNABLE_TO_EXEC_QUERY      = 104
	VERIFICATION_BODY_INCOMPLETE           = 105
	VERIFICATION_UNABLE_TO_EXEC_QUERY      = 106
	LOGIN_INCOMPLETE_CREDENTIALS           = 107
	LOGIN_PASSWORD_NOT_MATCH_OR_UNVERIFIED = 108
	LOGIN_JWT_ERROR                        = 109
	FORGET_PASSWORD_INCOMPLETE_CREDENTIALS = 110
	FORGET_PASSWORD_UNABLE_TO_EXEC_QUERY   = 111
	RESET_PASSWORD_PASSWORD_NOT_MATCH      = 112
	RESET_PASSWORD_UNABLE_TO_EXEC_QUERY    = 113
	TOKEN_NOT_PROVIDED                     = 114
	TOKEN_CANNOT_BE_FOUND                  = 115
	TOKEN_INVALID_SIGNATURE                = 116
	TOKEN_INVALID_CONTENT                  = 117
	TOKEN_EXPIRED                          = 118
	TOKEN_EMAIL_DOES_NOT_EXIST             = 119
)
