package auth

const (
	REGISTRATION_BODY_UNDECODABLE     = 100
	REGISTRATION_BODY_INCOMPLETE      = 101
	REGISTRATION_PASSWORD_NOT_MATCH   = 102
	REGISTRATION_UNABLE_TO_EXEC_QUERY = 103
	VERIFICATION_BODY_INCOMPLETE      = 104
	VERIFICATION_UNABLE_TO_EXEC_QUERY = 105
	LOGIN_INCOMPLETE_CREDENTIALS      = 106
	LOGIN_PASSWORD_DOES_NOT_MATCH     = 107
)
